version: '3.7'
services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    volumes:
      - ./volumes/db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --sql-mode=""
    ports:
      - '3307:3306'
    networks:
      - docker-net
    environment:
      - MYSQL_ROOT_PASSWORD=password

  mqtt5:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./volumes/mqtt/config:/mosquitto/config:rw
      - ./volumes/mqtt/data:/mosquitto/data:rw
      - ./volumes/mqtt/log:/mosquitto/log:rw
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge

volumes:
  dbdata:
    driver: local

